### ISSUE TITLE
Locator Changes:  March 2022

### ISSUE THREAD

**Issue by jamiemiller1486** [LANResources/dealer-locator#6]
Need to add a legend that defines the difference between a normal dealer and a Master Dealer

"Orange pin = BioZyme Master Dealer.  Certified as having extensive product knowledge and many products available"
" Purple pin = BioZyme Dealer"  

Please contact individual dealers for current product offerings and available inventory.

![image](https://user-images.githubusercontent.com/1561832/160910520-74685e1a-e081-4bc4-8ffa-1b3729aad23d.png)

**Comment by reed** [comment]
Thoughts on this?

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/672142/163023191-c646a958-70c4-4c05-b02f-21faa8733518.png">

I think it looks and functions better as part of the map, instead of below it.  But that doesn't leave any room for the additional text you wanted.  That text is already shown in the sidebar and when clicking on a master dealer marker, though.

**Comment by jamiemiller1486** [comment]
So would you add the statement: Please contact individual dealers for current product offerings and available inventory.

here...
![image](https://user-images.githubusercontent.com/1561832/163025077-230edf45-cb2f-4f15-adef-21adc24e84c9.png)

**Comment by reed** [comment]
I feel like there's already a lot going on there.  How about this:

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/672142/163026925-60dcacbc-94cd-4cd7-8e49-7de5e7dc6648.png">

I can add back the "Legend" title if you think that'd be better.

**Comment by jamiemiller1486** [comment]
works for me.
